# Generated by Django 3.2 on 2021-04-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210430_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
