# Generated by Django 3.2 on 2021-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210501_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
