# Generated by Django 3.1.7 on 2021-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210507_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(default='Photo', max_length=300),
        ),
    ]
